using System.Collections.Generic;

namespace QFramework.Gungeon
{
    public class Lv1Rooms
    {
        public static List<RoomConfig> normalRooms = new List<RoomConfig>()
        {
            new RoomConfig()
            .Type(RoomTypes.Normal)
            .L("111111111d111111111")
            .L("1                 1")
            .L("1                 1")
            .L("1   e        e    1")
            .L("1                 1")
            .L("1                 1")
            .L("1                 1")
            .L("1        e        1")
            .L("d       e1e       d")
            .L("1        e        1")
            .L("1                 1")
            .L("1                 1")
            .L("1                 1")
            .L("1                 1")
            .L("1                 1")
            .L("1   e        e    1")
            .L("1                 1")
            .L("1                 1")
            .L("111111111d111111111"),
            new RoomConfig()
            .Type(RoomTypes.Normal)
            .L("111111111d111111111")
            .L("1                 1")
            .L("1                 1")
            .L("1   1e      e1    1")
            .L("1   e        e    1")
            .L("1                 1")
            .L("1                 1")
            .L("1                 1")
            .L("d        1        d")
            .L("1                 1")
            .L("1                 1")
            .L("1                 1")
            .L("1                 1")
            .L("1                 1")
            .L("1   e        e    1")
            .L("1   1e      e1    1")
            .L("1                 1")
            .L("1                 1")
            .L("111111111d111111111"),
            new RoomConfig()
            .Type(RoomTypes.Normal)
            .L("111111111d111111111")
            .L("1                 1")
            .L("1                 1")
            .L("1   1111  1111    1")
            .L("1   1        1    1")
            .L("1   1        1    1")
            .L("1   1        1    1")
            .L("1       eee       1")
            .L("d       eee       d")
            .L("1       eee       1")
            .L("1   1        1    1")
            .L("1   1        1    1")
            .L("1   1        1    1")
            .L("1   1        1    1")
            .L("1   1        1    1")
            .L("1   1111  1111    1")
            .L("1                 1")
            .L("1                 1")
            .L("111111111d111111111"),
        };
    }
}